---
sudo: false
language: rust
rust:
    - stable
    - beta
    - nightly
env:
    - RUST_BACKTRACE=1
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
    include:
      - rust: stable
        os: osx
